name: Deploy To EC2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connects by SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: false
          script: |
            cd ~/lol-hae-duo
            
            if [ -d .git ]; then
              git reset --hard
              git pull origin dev
            else
              git clone https://github.com/team-summoner/lol-hae-duo.git .
              git checkout dev
            fi
            
            ./gradlew clean build
            
            # 기존 프로세스 종료 후 대기
            sudo fuser -k -n tcp 8080 || true
            sleep 3

            # 환경 변수 설정 후 실행
            nohup bash -c '
              export RIOT_API_KEY=${{ secrets.RIOT_API_KEY }}
              export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
              export MYSQL_URL=${{ secrets.MYSQL_URL }}
              export MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
              export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
              java -Dspring.profiles.active=prod -jar build/libs/lol-hae-duo-0.0.1-SNAPSHOT.jar
            ' > app.log 2>&1 &
